name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GO_VERSION: 1.23.8

jobs:
  ci:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install dependencies
      run: go mod tidy

    - name: Run format check
      run: make fmt

    - name: Run static analysis
      run: make vet

    - name: Run tests
      run: make test

    - name: Build binary
      run: make build